export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const SET_THONG_TIN_TAI_KHOAN = "SET_THONG_TIN_TAI_KHOAN";
export const SET_DANH_SACH_NGUOI_DUNG = "SET_DANH_SACH_NGUOI_DUNG";
export const LAY_LOAI_NGUOI_DUNG = "LAY_LOAI_NGUOI_DUNG";
export const SET_THONG_TIN_USER = "SET_THONG_TIN_USER";
